export type MediaCatalogKind = "movie" | "tv";

export interface MediaCatalogEntry {
  id: string;
  kind: MediaCatalogKind;
  title: string;
  cover: string;
  rating: number;
  year: string;
  genres: string[];
  progress: string;
  updatedAt: string;
}

const UPDATED_AT = "2026-07-25";

export const mediaCatalogEntries: MediaCatalogEntry[] = [
  {
    id: "1292052",
    kind: "movie",
    title: "肖申克的救赎",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p480747492.jpg",
    rating: 9.7,
    year: "1994",
    genres: ["剧情", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291546",
    kind: "movie",
    title: "霸王别姬",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2911205318.jpg",
    rating: 9.6,
    year: "1993",
    genres: ["剧情", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292722",
    kind: "movie",
    title: "泰坦尼克号",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p457760035.jpg",
    rating: 9.5,
    year: "1997",
    genres: ["剧情", "爱情", "灾难"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292720",
    kind: "movie",
    title: "阿甘正传",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p510876609.jpg",
    rating: 9.5,
    year: "1994",
    genres: ["剧情", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291561",
    kind: "movie",
    title: "千与千寻",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2557573348.jpg",
    rating: 9.4,
    year: "2001",
    genres: ["剧情", "动画", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1889243",
    kind: "movie",
    title: "星际穿越",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2614988097.jpg",
    rating: 9.4,
    year: "2014",
    genres: ["剧情", "科幻", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292063",
    kind: "movie",
    title: "美丽人生",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2578474613.jpg",
    rating: 9.5,
    year: "1997",
    genres: ["剧情", "喜剧", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1295644",
    kind: "movie",
    title: "这个杀手不太冷",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2913554676.jpg",
    rating: 9.4,
    year: "1994",
    genres: ["剧情", "动作", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3541415",
    kind: "movie",
    title: "盗梦空间",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p513344864.jpg",
    rating: 9.4,
    year: "2010",
    genres: ["剧情", "科幻", "悬疑"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292064",
    kind: "movie",
    title: "楚门的世界",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p479682972.jpg",
    rating: 9.4,
    year: "1998",
    genres: ["剧情", "科幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1295124",
    kind: "movie",
    title: "辛德勒的名单",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p492406163.jpg",
    rating: 9.5,
    year: "1993",
    genres: ["剧情", "历史", "战争"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3011091",
    kind: "movie",
    title: "忠犬八公的故事",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2587099240.jpg",
    rating: 9.4,
    year: "2009",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292001",
    kind: "movie",
    title: "海上钢琴师",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2914698334.jpg",
    rating: 9.3,
    year: "1998",
    genres: ["剧情", "音乐"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "25662329",
    kind: "movie",
    title: "疯狂动物城",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2924128964.jpg",
    rating: 9.3,
    year: "2016",
    genres: ["喜剧", "动画", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3793023",
    kind: "movie",
    title: "三傻大闹宝莱坞",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p579729551.jpg",
    rating: 9.2,
    year: "2009",
    genres: ["剧情", "喜剧", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2131459",
    kind: "movie",
    title: "机器人总动员",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p1461851991.jpg",
    rating: 9.3,
    year: "2008",
    genres: ["科幻", "动画", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291549",
    kind: "movie",
    title: "放牛班的春天",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2884280708.jpg",
    rating: 9.3,
    year: "2004",
    genres: ["剧情", "音乐"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1307914",
    kind: "movie",
    title: "无间道",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2597979873.jpg",
    rating: 9.3,
    year: "2002",
    genres: ["剧情", "惊悚", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1296141",
    kind: "movie",
    title: "控方证人",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2927451337.jpg",
    rating: 9.6,
    year: "1957",
    genres: ["剧情", "悬疑", "惊悚"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "20495023",
    kind: "movie",
    title: "寻梦环游记",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2505426431.jpg",
    rating: 9.1,
    year: "2017",
    genres: ["喜剧", "动画", "音乐"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292213",
    kind: "movie",
    title: "大话西游之大圣娶亲",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2455050536.jpg",
    rating: 9.2,
    year: "1995",
    genres: ["喜剧", "爱情", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "5912992",
    kind: "movie",
    title: "熔炉",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p1363250216.jpg",
    rating: 9.3,
    year: "2011",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "6786002",
    kind: "movie",
    title: "触不可及",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p1454261925.jpg",
    rating: 9.3,
    year: "2011",
    genres: ["剧情", "喜剧"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291841",
    kind: "movie",
    title: "教父",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p616779645.jpg",
    rating: 9.3,
    year: "1972",
    genres: ["剧情", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1293172",
    kind: "movie",
    title: "末代皇帝",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p452089833.jpg",
    rating: 9.3,
    year: "1987",
    genres: ["剧情", "传记", "历史"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1295038",
    kind: "movie",
    title: "哈利·波特与魔法石",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2913781448.jpg",
    rating: 9.2,
    year: "2001",
    genres: ["奇幻", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1849031",
    kind: "movie",
    title: "当幸福来敲门",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2220721286.jpg",
    rating: 9.1,
    year: "2006",
    genres: ["剧情", "家庭", "传记"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291560",
    kind: "movie",
    title: "龙猫",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2540924496.jpg",
    rating: 9.2,
    year: "1988",
    genres: ["动画", "奇幻", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292365",
    kind: "movie",
    title: "活着",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2597919477.jpg",
    rating: 9.3,
    year: "1994",
    genres: ["剧情", "家庭", "历史"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3319755",
    kind: "movie",
    title: "怦然心动",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p501177648.jpg",
    rating: 9.1,
    year: "2010",
    genres: ["剧情", "喜剧", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1851857",
    kind: "movie",
    title: "蝙蝠侠：黑暗骑士",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p462657443.jpg",
    rating: 9.2,
    year: "2008",
    genres: ["剧情", "动作", "科幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291552",
    kind: "movie",
    title: "指环王3：王者无敌",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2642829472.jpg",
    rating: 9.3,
    year: "2003",
    genres: ["剧情", "动作", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "26752088",
    kind: "movie",
    title: "我不是药神",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2527119568.jpg",
    rating: 9.0,
    year: "2018",
    genres: ["剧情", "喜剧"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1300267",
    kind: "movie",
    title: "乱世佳人",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p1963126880.jpg",
    rating: 9.3,
    year: "1939",
    genres: ["剧情", "爱情", "历史"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3742360",
    kind: "movie",
    title: "让子弹飞",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1512562287.jpg",
    rating: 9.0,
    year: "2010",
    genres: ["剧情", "喜剧", "动作"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2129039",
    kind: "movie",
    title: "飞屋环游记",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p485887754.jpg",
    rating: 9.1,
    year: "2009",
    genres: ["剧情", "喜剧", "动画"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1308807",
    kind: "movie",
    title: "哈尔的移动城堡",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2907583906.jpg",
    rating: 9.1,
    year: "2004",
    genres: ["爱情", "动画", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1293182",
    kind: "movie",
    title: "十二怒汉",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2173577632.jpg",
    rating: 9.4,
    year: "1957",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "25958717",
    kind: "movie",
    title: "海蒂和爷爷",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2554525534.jpg",
    rating: 9.3,
    year: "2015",
    genres: ["剧情", "家庭", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "21937452",
    kind: "movie",
    title: "素媛",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2118532944.jpg",
    rating: 9.3,
    year: "2013",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1305487",
    kind: "movie",
    title: "猫鼠游戏",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p453924541.jpg",
    rating: 9.1,
    year: "2002",
    genres: ["剧情", "传记", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291583",
    kind: "movie",
    title: "天空之城",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2892409201.jpg",
    rating: 9.2,
    year: "1986",
    genres: ["动画", "奇幻", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291858",
    kind: "movie",
    title: "鬼子来了",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2930874010.jpg",
    rating: 9.3,
    year: "2000",
    genres: ["剧情", "喜剧"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "26387939",
    kind: "movie",
    title: "摔跤吧！爸爸",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2401676338.jpg",
    rating: 9.0,
    year: "2016",
    genres: ["剧情", "家庭", "传记"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1929463",
    kind: "movie",
    title: "少年派的奇幻漂流",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p1784592701.jpg",
    rating: 9.1,
    year: "2012",
    genres: ["剧情", "奇幻", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1296736",
    kind: "movie",
    title: "钢琴家",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p1381339291.jpg",
    rating: 9.3,
    year: "2002",
    genres: ["剧情", "音乐", "传记"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291548",
    kind: "movie",
    title: "死亡诗社",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2575465690.jpg",
    rating: 9.2,
    year: "1989",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291572",
    kind: "movie",
    title: "指环王2：双塔奇兵",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2640236255.jpg",
    rating: 9.2,
    year: "2002",
    genres: ["剧情", "动作", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1299398",
    kind: "movie",
    title: "大话西游之月光宝盒",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2561721372.jpg",
    rating: 9.0,
    year: "1995",
    genres: ["喜剧", "爱情", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "27060077",
    kind: "movie",
    title: "绿皮书",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2531065411.jpg",
    rating: 8.9,
    year: "2018",
    genres: ["剧情", "喜剧", "音乐"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "30170448",
    kind: "movie",
    title: "何以为家",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2875749222.jpg",
    rating: 9.1,
    year: "2018",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1298624",
    kind: "movie",
    title: "闻香识女人",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2550757929.jpg",
    rating: 9.1,
    year: "1992",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1418019",
    kind: "movie",
    title: "大闹天宫",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2184505167.jpg",
    rating: 9.4,
    year: "1961",
    genres: ["剧情", "动画", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291843",
    kind: "movie",
    title: "黑客帝国",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p451926968.jpg",
    rating: 9.1,
    year: "1999",
    genres: ["动作", "科幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291571",
    kind: "movie",
    title: "指环王1：护戒使者",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2197698335.jpg",
    rating: 9.1,
    year: "2001",
    genres: ["剧情", "动作", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1293839",
    kind: "movie",
    title: "罗马假日",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2189265085.jpg",
    rating: 9.1,
    year: "1953",
    genres: ["剧情", "喜剧", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1299131",
    kind: "movie",
    title: "教父2",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2194138787.jpg",
    rating: 9.3,
    year: "1974",
    genres: ["剧情", "犯罪"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1301753",
    kind: "movie",
    title: "狮子王",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p726659067.jpg",
    rating: 9.1,
    year: "1994",
    genres: ["动画", "歌舞", "冒险"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291828",
    kind: "movie",
    title: "天堂电影院",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2653054340.jpg",
    rating: 9.2,
    year: "1988",
    genres: ["剧情", "爱情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1291818",
    kind: "movie",
    title: "饮食男女",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p1910899751.jpg",
    rating: 9.2,
    year: "1994",
    genres: ["剧情", "家庭"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "21937445",
    kind: "movie",
    title: "辩护人",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2158166535.jpg",
    rating: 9.2,
    year: "2013",
    genres: ["剧情"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1485260",
    kind: "movie",
    title: "本杰明·巴顿奇事",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2192535722.jpg",
    rating: 9.0,
    year: "2008",
    genres: ["剧情", "爱情", "奇幻"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1292000",
    kind: "movie",
    title: "搏击俱乐部",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1910931622.jpg",
    rating: 9.0,
    year: "1999",
    genres: ["剧情", "动作", "悬疑"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1306029",
    kind: "movie",
    title: "美丽心灵",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p1665997400.jpg",
    rating: 9.1,
    year: "2001",
    genres: ["剧情", "传记"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3008247",
    kind: "movie",
    title: "穿条纹睡衣的男孩",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1473670352.jpg",
    rating: 9.2,
    year: "2008",
    genres: ["剧情", "战争"],
    progress: "豆瓣 Top 250",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36680492",
    kind: "movie",
    title: "大濛",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2925804842.jpg",
    rating: 8.2,
    year: "2025",
    genres: ["剧情"],
    progress: "近期电影",
    updatedAt: UPDATED_AT,
  },
  {
    id: "35010610",
    kind: "movie",
    title: "挽救计划",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2931370692.jpg",
    rating: 8.6,
    year: "2026",
    genres: ["剧情", "科幻", "惊悚"],
    progress: "近期电影",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36474027",
    kind: "movie",
    title: "镖人：风起大漠",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2929760596.jpg",
    rating: 7.5,
    year: "2026",
    genres: ["动作", "武侠", "古装"],
    progress: "近期电影",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36956594",
    kind: "movie",
    title: "穿普拉达的女王2",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2930952195.jpg",
    rating: 6.4,
    year: "2026",
    genres: ["剧情", "喜剧"],
    progress: "近期电影",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36877245",
    kind: "movie",
    title: "火遮眼",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2932757540.jpg",
    rating: 7.7,
    year: "2025",
    genres: ["动作", "犯罪"],
    progress: "近期电影",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1864810",
    kind: "tv",
    title: "红楼梦",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2554030915.jpg",
    rating: 9.7,
    year: "1987",
    genres: ["剧情", "爱情", "古装"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2156663",
    kind: "tv",
    title: "西游记",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2265959269.jpg",
    rating: 9.7,
    year: "1986",
    genres: ["剧情", "动作", "奇幻"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1441794",
    kind: "tv",
    title: "走向共和",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2328449064.jpg",
    rating: 9.6,
    year: "2003",
    genres: ["剧情", "历史"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2210001",
    kind: "tv",
    title: "大明王朝1566",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2444453078.jpg",
    rating: 9.8,
    year: "2007",
    genres: ["剧情", "历史", "古装"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "26603847",
    kind: "tv",
    title: "毛骗 终结篇",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2480805230.jpg",
    rating: 9.7,
    year: "2015",
    genres: ["悬疑", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3882715",
    kind: "tv",
    title: "武林外传",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2529669661.jpg",
    rating: 9.6,
    year: "2006",
    genres: ["喜剧", "武侠", "古装"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "25754848",
    kind: "tv",
    title: "琅琊榜",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2271982968.jpg",
    rating: 9.4,
    year: "2015",
    genres: ["剧情", "古装"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "4922787",
    kind: "tv",
    title: "后宫·甄嬛传",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1480046723.jpg",
    rating: 9.4,
    year: "2011",
    genres: ["剧情", "古装"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "19965220",
    kind: "tv",
    title: "父母爱情",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2892197648.jpg",
    rating: 9.3,
    year: "2014",
    genres: ["爱情", "家庭"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "35588177",
    kind: "tv",
    title: "漫长的季节",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2890906384.jpg",
    rating: 9.4,
    year: "2023",
    genres: ["剧情", "家庭", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "34874646",
    kind: "tv",
    title: "繁花",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2902705337.jpg",
    rating: 8.7,
    year: "2023",
    genres: ["剧情", "爱情"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "33447642",
    kind: "tv",
    title: "沉默的真相",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2620780603.jpg",
    rating: 9.0,
    year: "2020",
    genres: ["剧情", "悬疑", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "33404425",
    kind: "tv",
    title: "隐秘的角落",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2609064048.jpg",
    rating: 8.8,
    year: "2020",
    genres: ["剧情", "悬疑", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "26883064",
    kind: "tv",
    title: "白夜追凶",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2483150767.jpg",
    rating: 8.9,
    year: "2017",
    genres: ["剧情", "悬疑", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "26302614",
    kind: "tv",
    title: "请回答1988",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2272563445.jpg",
    rating: 9.7,
    year: "2015",
    genres: ["剧情", "喜剧", "爱情"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "3016187",
    kind: "tv",
    title: "权力的游戏 第一季",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p896064368.jpg",
    rating: 9.5,
    year: "2011",
    genres: ["剧情", "奇幻", "冒险"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "6952149",
    kind: "tv",
    title: "绝命毒师 第五季",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1579021082.jpg",
    rating: 9.7,
    year: "2012",
    genres: ["剧情", "犯罪"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2154096",
    kind: "tv",
    title: "士兵突击",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p2240922426.jpg",
    rating: 9.5,
    year: "2006",
    genres: ["剧情"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1307847",
    kind: "tv",
    title: "兄弟连",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p1714777727.jpg",
    rating: 9.6,
    year: "2001",
    genres: ["剧情", "动作", "历史"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "1393859",
    kind: "tv",
    title: "老友记 第一季",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2186920269.jpg",
    rating: 9.7,
    year: "1994",
    genres: ["喜剧", "爱情"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "2156528",
    kind: "tv",
    title: "生活大爆炸 第一季",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2553281898.jpg",
    rating: 9.5,
    year: "2007",
    genres: ["喜剧"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "7054120",
    kind: "tv",
    title: "黑镜 第一季",
    cover: "https://img9.doubanio.com/view/photo/m_ratio_poster/public/p1403875505.jpg",
    rating: 9.4,
    year: "2011",
    genres: ["剧情", "科幻", "惊悚"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "6037429",
    kind: "tv",
    title: "纸牌屋 第一季",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2162615597.jpg",
    rating: 9.3,
    year: "2013",
    genres: ["剧情"],
    progress: "高分剧集",
    updatedAt: UPDATED_AT,
  },
  {
    id: "37071123",
    kind: "tv",
    title: "铁拳教育",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2933103931.jpg",
    rating: 8.7,
    year: "2026",
    genres: ["剧情", "动作"],
    progress: "近期热播",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36618951",
    kind: "tv",
    title: "野狗骨头",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2933763712.jpg",
    rating: 6.9,
    year: "2026",
    genres: ["剧情", "爱情"],
    progress: "32 集全",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36624136",
    kind: "tv",
    title: "悬案",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2933759962.jpg",
    rating: 7.5,
    year: "2026",
    genres: ["剧情", "悬疑", "犯罪"],
    progress: "17 集全",
    updatedAt: UPDATED_AT,
  },
  {
    id: "35517044",
    kind: "tv",
    title: "低智商犯罪",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2932040107.jpg",
    rating: 8.2,
    year: "2026",
    genres: ["剧情", "犯罪"],
    progress: "近期热播",
    updatedAt: UPDATED_AT,
  },
  {
    id: "35295564",
    kind: "tv",
    title: "主角",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2932204747.jpg",
    rating: 8.1,
    year: "2026",
    genres: ["剧情"],
    progress: "国产剧",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36666949",
    kind: "tv",
    title: "龙之家族 第三季",
    cover: "https://img2.doubanio.com/view/photo/m_ratio_poster/public/p2932193011.jpg",
    rating: 8.2,
    year: "2026",
    genres: ["剧情", "动作", "爱情"],
    progress: "美剧",
    updatedAt: UPDATED_AT,
  },
  {
    id: "37415674",
    kind: "tv",
    title: "熊家餐馆 第五季",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2932198629.jpg",
    rating: 8.6,
    year: "2026",
    genres: ["剧情", "喜剧"],
    progress: "美剧",
    updatedAt: UPDATED_AT,
  },
  {
    id: "36858672",
    kind: "tv",
    title: "星城",
    cover: "https://img1.doubanio.com/view/photo/m_ratio_poster/public/p2931843898.jpg",
    rating: 8.5,
    year: "2026",
    genres: ["剧情", "科幻", "战争"],
    progress: "美剧",
    updatedAt: UPDATED_AT,
  },
  {
    id: "37335468",
    kind: "tv",
    title: "努力克服自卑的我们",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2931033503.jpg",
    rating: 8.6,
    year: "2026",
    genres: ["剧情"],
    progress: "韩剧",
    updatedAt: UPDATED_AT,
  },
  {
    id: "37523009",
    kind: "tv",
    title: "金特务：本色回归",
    cover: "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2933197483.jpg",
    rating: 7.7,
    year: "2026",
    genres: ["动作", "惊悚", "犯罪"],
    progress: "韩剧",
    updatedAt: UPDATED_AT,
  },
];

const mediaById = new Map(mediaCatalogEntries.map((entry) => [entry.id, entry]));

export function getMediaCatalogEntry(id: string): MediaCatalogEntry | undefined {
  return mediaById.get(id);
}

export function getMediaCatalogPath(entry: MediaCatalogEntry): string {
  return `/media/${entry.id}`;
}

export function getMediaKindLabel(kind: MediaCatalogKind): string {
  return kind === "movie" ? "电影" : "电视剧";
}

export function getMediaSeoTitle(entry: MediaCatalogEntry): string {
  return `${entry.title}网盘资源搜索与版本说明 - 好搜库`;
}

export function getMediaDescription(entry: MediaCatalogEntry): string {
  const kind = getMediaKindLabel(entry.kind);
  return `查找${entry.year}年${kind}《${entry.title}》的公开网盘索引，按夸克、115、百度等平台搜索，并核对${entry.kind === "movie" ? "清晰度、字幕、音轨和文件版本" : "集数、字幕、更新时间和完结状态"}。`;
}

export function getMediaSearchExamples(entry: MediaCatalogEntry): string[] {
  const core = entry.year ? `${entry.title} ${entry.year}` : entry.title;
  if (entry.kind === "tv") {
    return [
      `${entry.title} 全集`,
      `${entry.title} 夸克网盘`,
      `${entry.title} 115网盘`,
      `${entry.title} 百度网盘`,
      `${core} 高清`,
    ];
  }
  return [
    `${entry.title} 网盘资源`,
    `${entry.title} 夸克网盘`,
    `${entry.title} 115网盘`,
    `${entry.title} 百度网盘`,
    `${core} 4K 中文字幕`,
  ];
}

export function getRelatedMedia(
  entry: MediaCatalogEntry,
  limit = 6
): MediaCatalogEntry[] {
  return mediaCatalogEntries
    .filter((candidate) => candidate.id !== entry.id)
    .map((candidate) => ({
      candidate,
      score:
        (candidate.kind === entry.kind ? 4 : 0) +
        candidate.genres.filter((genre) => entry.genres.includes(genre)).length * 3 +
        Math.max(0, 2 - Math.abs(Number(candidate.year) - Number(entry.year)) / 10),
    }))
    .sort(
      (left, right) =>
        right.score - left.score ||
        right.candidate.rating - left.candidate.rating ||
        left.candidate.id.localeCompare(right.candidate.id)
    )
    .slice(0, limit)
    .map(({ candidate }) => candidate);
}
